@startuml
'https://plantuml.com/use-case-diagram
:User: as User
:Client: as Client
:Worker: as Worker
:Manager: as Manager

left to right direction

User -->(Перегляд меню)
User -->(Реєстрація)
User -->(Авторизація)
Client -->(Перегляд меню)
Client -->(Вибір страв)
Client-->(Коректування замовлення)
Client-->(Відправка замовлення)
Client-->(Слідкувати за статусум замовлення)
Client-->(Видача замовлення Працівником)
Worker -->(Авторизація працівника)
Worker -->(Перегляд списку замовлень)
Worker -->(Зміна статусу замовлення)
Worker -->(Перегляд власної статистики)
Worker -->(Видача замовлення Працівником)
Manager -->(Авторизація працівника)
Manager -->(Видалення працівників)
Manager -->(Перегляд статистики)
Manager -->(Редагування меню)
Manager -->(Взаємодія через службу підтримки)






@enduml